name: CI

on:
  push:
    branches: [ main, chore/**, feat/**, fix/** ]
  pull_request:
    branches: [ main ]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install uv
      - name: Sync deps
        run: uv sync
      - name: Run unit tests
        env:
          OPENAI_API_KEY: dummy
        run: uv run pytest -q tests/unit

  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci --ignore-scripts
      - name: Typecheck
        run: npx tsc -v && npx tsc --noEmit
      - name: Lint
        run: npx -y eslint . || true
