name: CI

on:
  push:
    branches: [ main, chore/**, feat/**, fix/** ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Type check
        run: npx tsc --noEmit
      - name: Lint
        run: npx eslint . --ext .ts,.tsx,.js,.jsx
      - name: Build
        run: npm run build
